/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "DisplayTimer.h"
#include "Timer_CLK.h"
#include "Disp_INT.h"
#include "BLE_gatt.h"
#include "BLE.h"
#include "BLE_HAL_PVT.h"
#include "BLE_STACK_PVT.h"
#include "BLE_StackGap.h"
#include "BLE_StackGatt.h"
#include "BLE_StackGattDb.h"
#include "BLE_StackHostMain.h"
#include "BLE_StackL2cap.h"
#include "BLE_StackGattServer.h"
#include "BLE_StackGattClient.h"
#include "BLE_Stack.h"
#include "BLE_eventHandler.h"
#include "BLE_custom.h"
#include "UART.h"
#include "UART_SPI_UART.h"
#include "UART_PINS.h"
#include "UART_SPI_UART_PVT.h"
#include "UART_PVT.h"
#include "UART_BOOT.h"
#include "flexSensorA.h"
#include "flexSensorA_aliases.h"
#include "flexSensorB.h"
#include "flexSensorB_aliases.h"
#include "adc.h"
#include "motorA.h"
#include "motorA_aliases.h"
#include "motorB.h"
#include "motorB_aliases.h"
#include "buzzer.h"
#include "buzzer_aliases.h"
#include "pwmBuzzer.h"
#include "clockBuzzer.h"
#include "uart2.h"
#include "BLE_bless_isr.h"
#include "UART_SCBCLK.h"
#include "UART_tx.h"
#include "UART_tx_aliases.h"
#include "UART_rx.h"
#include "UART_rx_aliases.h"
#include "adc_IRQ.h"
#include "adc_intClock.h"
#include "uart2_IntClock.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"

/*[]*/

