/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Pin_RedLED.h"
#include "Pin_RedLED_aliases.h"
#include "Pin_GreenLED.h"
#include "Pin_GreenLED_aliases.h"
#include "Pin_BlueLED.h"
#include "Pin_BlueLED_aliases.h"
#include "Clock_PWM.h"
#include "PWM_R.h"
#include "PWM_G.h"
#include "PWM_B.h"
#include "ADC.h"
#include "A0.h"
#include "A0_aliases.h"
#include "UART_1.h"
#include "ADC_IRQ.h"
#include "ADC_intClock.h"
#include "UART_1_IntClock.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"

/*[]*/

