/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "flexSensorA.h"
#include "flexSensorA_aliases.h"
#include "flexSensorB.h"
#include "flexSensorB_aliases.h"
#include "adc.h"
#include "motorA.h"
#include "motorA_aliases.h"
#include "motorB.h"
#include "motorB_aliases.h"
#include "buzzer.h"
#include "buzzer_aliases.h"
#include "pwmBuzzer.h"
#include "clockBuzzer.h"
#include "uart.h"
#include "adc_IRQ.h"
#include "adc_intClock.h"
#include "uart_IntClock.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"

/*[]*/

