/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "switch1_aliases.h"
#include "switch1.h"
#include "lcd.h"
#include "enc.h"
#include "enc_PVT.h"
#include "C1_aliases.h"
#include "C1.h"
#include "C2_aliases.h"
#include "C2.h"
#include "Clock_1.h"
#include "adc.h"
#include "pot_aliases.h"
#include "pot.h"
#include "lcd_LCDPort_aliases.h"
#include "lcd_LCDPort.h"
#include "enc_isr.h"
#include "enc_Cnt16.h"
#include "adc_SAR.h"
#include "adc_IntClock.h"
#include "adc_TempBuf_dma.h"
#include "adc_FinalBuf_dma.h"
#include "adc_IRQ.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

