# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\Jacob\Documents\Junior\EGR 304\EGR304\hw8_1.cydsn\hw8_1.cyprj
# Date: Wed, 08 Nov 2017 16:09:13 GMT
#set_units -time ns
create_clock -name {CyRouted1} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyWCO} -period 30517.578125 -waveform {0 15258.7890625} [list [get_pins {ClockBlock/wco}]]
create_clock -name {CyLFClk} -period 30517.578125 -waveform {0 15258.7890625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyECO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/eco}]]
create_clock -name {CyIMO} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFClk} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySysClk} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/sysclk}]]
create_generated_clock -name {uart_IntClock} -source [get_pins {ClockBlock/hfclk}] -edges {1 625 1251} -nominal_period 13020.833333333332 [list [get_pins {ClockBlock/udb_div_0}]]


# Component constraints for C:\Users\Jacob\Documents\Junior\EGR 304\EGR304\hw8_1.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\Jacob\Documents\Junior\EGR 304\EGR304\hw8_1.cydsn\hw8_1.cyprj
# Date: Wed, 08 Nov 2017 16:09:11 GMT
